# Generated by Django 5.2.3 on 2025-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price_type',
            field=models.CharField(choices=[('sale', 'Satiş qiyməti'), ('discount', 'Endirimli qiymət')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
