# Generated by Django 5.2.3 on 2025-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='price_type',
            field=models.CharField(choices=[('sale', 'Satiş qiyməti'), ('discount', 'Endirimli qiymət')], default='qiymeti daxil edin', max_length=100),
        ),
    ]
